export PYTHIA8DATA=${PYTHIA8_DIR}/share/Pythia8/xmldoc
export PYTHIAFCC=$PWD/install
export DYLD_LIBRARY_PATH=$PYTHIAFCC/lib:$HEPMC_PREFIX/lib:$FASTJET_ROOT_DIR/lib:$PYTHIA8_DIR/lib:$DYLD_LIBRARY_PATH
export PATH=$PYTHIAFCC/bin:$FASTJET_ROOT_DIR/bin:$PATH
